# this config was migrated from renv.lock on 2026-10-09
[project]
name = "api"
r_version = "4.6.1"

repositories = [
    { alias = "P3M", url = "https://packagemanager.posit.co/cran/latest"},
    { alias = "CRAN", url = "https://cloud.r-project.org/"}
]

dependencies = [
    { name = "DBI", repository = "P3M" },
    { name = "MatrixModels", repository = "P3M" },
    { name = "R6", repository = "P3M" },
    { name = "RColorBrewer", repository = "P3M" },
    { name = "Rcpp", repository = "P3M" },
    { name = "S7", repository = "P3M" },
    { name = "SparseM", repository = "P3M" },
    { name = "askpass", repository = "P3M" },
    { name = "backports", repository = "P3M" },
    { name = "base64enc", repository = "P3M" },
    { name = "bit", repository = "P3M" },
    { name = "bit64", repository = "CRAN" },
    { name = "blob", repository = "P3M" },
    { name = "broom", repository = "P3M" },
    { name = "bslib", repository = "P3M" },
    { name = "cachem", repository = "P3M" },
    { name = "callr", repository = "P3M" },
    { name = "cellranger", repository = "CRAN" },
    { name = "cli", repository = "P3M" },
    { name = "clipr", repository = "P3M" },
    { name = "commonmark", repository = "P3M" },
    { name = "conflicted", repository = "CRAN" },
    { name = "cpp11", repository = "P3M" },
    { name = "crayon", repository = "P3M" },
    { name = "crosstalk", repository = "P3M" },
    { name = "dbplyr", repository = "P3M" },
    { name = "digest", repository = "P3M" },
    { name = "doFuture", repository = "CRAN" },
    { name = "dplyr", repository = "P3M" },
    { name = "dtplyr", repository = "CRAN" },
    { name = "evaluate", repository = "P3M" },
    { name = "farver", repository = "P3M" },
    { name = "fastmap", repository = "P3M" },
    { name = "fontawesome", repository = "P3M" },
    { name = "forcats", repository = "P3M" },
    { name = "foreach", repository = "P3M" },
    { name = "forecast", repository = "CRAN" },
    { name = "fracdiff", repository = "CRAN" },
    { name = "fs", repository = "P3M" },
    { name = "future.apply", repository = "P3M" },
    { name = "gargle", repository = "CRAN" },
    { name = "generics", repository = "P3M" },
    { name = "ggplot2", repository = "P3M" },
    { name = "ggtext", repository = "CRAN" },
    { name = "globals", repository = "P3M" },
    { name = "glue", repository = "P3M" },
    { name = "googledrive", repository = "CRAN" },
    { name = "googlesheets4", repository = "CRAN" },
    { name = "gridtext", repository = "CRAN" },
    { name = "gtable", repository = "P3M" },
    { name = "haven", repository = "CRAN" },
    { name = "here", repository = "P3M" },
    { name = "highr", repository = "P3M" },
    { name = "hms", repository = "P3M" },
    { name = "htmltools", repository = "P3M" },
    { name = "htmlwidgets", repository = "P3M" },
    { name = "httr2", repository = "P3M" },
    { name = "ids", repository = "CRAN" },
    { name = "ihpdr", repository = "CRAN" },
    { name = "imputeTS", repository = "CRAN" },
    { name = "isoband", repository = "P3M" },
    { name = "iterators", repository = "P3M" },
    { name = "jpeg", repository = "P3M" },
    { name = "jquerylib", repository = "P3M" },
    { name = "jsonlite", repository = "P3M" },
    { name = "labeling", repository = "P3M" },
    { name = "later", repository = "P3M" },
    { name = "lazyeval", repository = "P3M" },
    { name = "lifecycle", repository = "P3M" },
    { name = "lmtest", repository = "CRAN" },
    { name = "lubridate", repository = "P3M" },
    { name = "magrittr", repository = "P3M" },
    { name = "markdown", repository = "P3M" },
    { name = "memoise", repository = "P3M" },
    { name = "mime", repository = "P3M" },
    { name = "modelr", repository = "CRAN" },
    { name = "nationwider", git = "https://github.com/kvasilopoulos/nationwider", commit = "ab26df18b63930e196bb061a6486a396ba3f8066" },
    { name = "openssl", repository = "P3M" },
    { name = "otel", repository = "P3M" },
    { name = "parallelly", repository = "P3M" },
    { name = "pillar", repository = "P3M" },
    { name = "pkgconfig", repository = "P3M" },
    { name = "plotly", repository = "CRAN" },
    { name = "png", repository = "P3M" },
    { name = "prettyunits", repository = "P3M" },
    { name = "processx", repository = "P3M" },
    { name = "progress", repository = "P3M" },
    { name = "progressr", repository = "P3M" },
    { name = "promises", repository = "P3M" },
    { name = "ps", repository = "P3M" },
    { name = "purrr", repository = "P3M" },
    { name = "quantreg", repository = "CRAN" },
    { name = "ragg", repository = "P3M" },
    { name = "rappdirs", repository = "P3M" },
    { name = "readr", repository = "P3M" },
    { name = "rematch", repository = "CRAN" },
    { name = "rematch2", repository = "CRAN" },
    { name = "remotes", repository = "P3M" },
    { name = "reprex", repository = "CRAN" },
    { name = "rlang", repository = "P3M" },
    { name = "rprojroot", repository = "P3M" },
    { name = "rstudioapi", repository = "P3M" },
    { name = "rvest", repository = "P3M" },
    { name = "sass", repository = "P3M" },
    { name = "scales", repository = "P3M" },
    { name = "stinepack", repository = "CRAN" },
    { name = "stringi", repository = "P3M" },
    { name = "stringr", repository = "P3M" },
    { name = "sys", repository = "P3M" },
    { name = "systemfonts", repository = "P3M" },
    { name = "textshaping", repository = "P3M" },
    { name = "tibble", repository = "P3M" },
    { name = "tidyr", repository = "P3M" },
    { name = "tidyselect", repository = "P3M" },
    { name = "tidyverse", repository = "CRAN" },
    { name = "timeDate", repository = "P3M" },
    { name = "timechange", repository = "P3M" },
    { name = "transx", repository = "CRAN" },
    { name = "tzdb", repository = "P3M" },
    { name = "uklr", git = "https://github.com/kvasilopoulos/uklr", commit = "80a64e92da7f7e32fef41b9ad038721d3b38d2d4" },
    { name = "urca", repository = "CRAN" },
    { name = "utf8", repository = "P3M" },
    { name = "uuid", repository = "CRAN" },
    { name = "vctrs", repository = "P3M" },
    { name = "viridisLite", repository = "P3M" },
    { name = "vroom", repository = "P3M" },
    { name = "withr", repository = "P3M" },
    { name = "xml2", repository = "P3M" },
    { name = "yaml", repository = "P3M" },
    { name = "ivx", git = "https://github.com/kvasilopoulos/ivx", branch = "master" },
    "RcppArmadillo",
    "colorspace",
    "curl",
    "data.table",
    "future",
    "httr",
    "knitr",
    "listenv",
    "litedown",
    "readxl",
    "rmarkdown",
    "selectr",
    "tinytex",
    "xfun",
    "zoo",
    "exuber",
]
